# fly.toml app configuration file generated for leptos-cv-fragrant-wave-2284 on 2023-12-03T11:36:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "leptos-cv"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
