name: Deploy

on:
  push:
    branches:
      - main

jobs:
  check_commit_message:
    name: Check Commit Message
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Commit Message
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ "feat:" || "${{ github.event.head_commit.message }}" =~ "fix:" || "${{ github.event.head_commit.message }}" =~ "chore:" ]]; then
            echo "Commit message contains 'feat', 'fix' or 'chore', proceeding with deployment..."
          else
            echo "Commit message does not contain 'feat' or 'fix', skipping deployment."
            exit 78
          fi

  deploy:
    name: Deploy CV
    runs-on: ubuntu-latest

    needs: check_commit_message

    if: contains(github.event.head_commit.message, 'feat') || contains(github.event.head_commit.message, 'fix')

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
